# Generated by Django 3.2.4 on 2022-05-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Book Chapter', 'verbose_name_plural': 'Book Chapters'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='book',
            name='font',
            field=models.CharField(default='Times New Roman', max_length=50, verbose_name='Book Font'),
        ),
        migrations.AlterField(
            model_name='book',
            name='blurb',
            field=models.TextField(max_length=500, verbose_name='Book Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='cover_images', verbose_name='Book Cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Book Name'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Chapter Title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='chapter_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.chapter', verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_post',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Commenter Name'),
        ),
    ]
